version: 2

jobs:
  unitTests:
    docker:
      - image: node:12.16.1-alpine3.11
    steps:
      - checkout
      - run: yarn
      - run:
          name: Run unit tests
          command: |
            yarn test

  e2eTests:
    docker:
      - image: node:12.16.1-alpine3.11
      - image: parity/polkadot:v0.7.28
        name: polkadot
        command: --dev --ws-port 11000 --unsafe-ws-external
    steps:
      - checkout
      - run: yarn
      - run:
          name: Run e2e tests
          command: |
            yarn test

  buildImage:
    docker:
      - image: web3f/ci-commons:v2.0.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            /scripts/build-image.sh web3f/accountant .

  helmLint:
    docker:
      - image: web3f/ci-commons:v2.0.1
    steps:
      - checkout
      - run:
          command: |
            helm lint ./charts/accountant

  integrationTests:
    docker:
      - image: web3f/ci-commons:v2.0.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          description: run integration tests
          command: |
            /scripts/integration-tests.sh

  publishImage:
    docker:
      - image: web3f/ci-commons:v2.0.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            /scripts/publish-image.sh web3f/accountant

  publishChart:
    docker:
      - image: web3f/ci-commons:v2.0.1
    steps:
      - checkout
      - run:
          command: |
            /scripts/publish-chart.sh

  deploy:
    docker:
      - image: web3f/ci-commons:v2.0.1
    steps:
      - checkout
      - run:
          environment:
            HELM_ENV: production
            GCP_REGION: europe-west3
          command: |
            /scripts/deploy.sh -c engineering

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - unitTests:
          filters:
            tags:
              only: /.*/
      - e2eTests:
          filters:
            tags:
              only: /.*/
      - helmLint:
          filters:
            tags:
              only: /.*/
      - buildImage:
          filters:
            tags:
              only: /.*/
          requires:
            - unitTests
            - e2eTests
      - integrationTests:
          filters:
            tags:
              only: /.*/
          requires:
            - buildImage
            - helmLint
      - publishImage:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          requires:
            - integrationTests
      - publishChart:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          requires:
            - integrationTests
      - deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          requires:
            - publishImage
            - publishChart
