logLevel: info
wsEndpoint: "wss://kusama-rpc.polkadot.io/"
transactions:
- sender:
    alias: validator-000
    keystore:
      filePath: /home/fgimenez/workspace/w3f/validator-scripts/keystores/stash-0.json
      passwordPath: /home/fgimenez/Desktop/accountant/prodpass.txt
  receiver:
    alias: validator-rewards
    address: 5DUnd4VPKWqEnbMEJ7CSnDUdikVkbfFZ6UqqJUAcgjf8g6ab
  restriction:
    remaining: 10000000000000 # leave this much in the sender, send the rest
- sender:
    alias: validator-001
    keystore:
      filePath: /home/fgimenez/workspace/w3f/validator-scripts/keystores/stash-1.json
      passwordPath: /home/fgimenez/Desktop/accountant/prodpass.txt
  receiver:
    alias: validator-rewards
    address: 5DUnd4VPKWqEnbMEJ7CSnDUdikVkbfFZ6UqqJUAcgjf8g6ab
  restriction:
    remaining: 10000000000000 # leave this much in the sender, send the rest
- sender:
    alias: validator-002
    keystore:
      filePath: /home/fgimenez/workspace/w3f/validator-scripts/keystores/stash-2.json
      passwordPath: /home/fgimenez/Desktop/accountant/prodpass.txt
  receiver:
    alias: validator-rewards
    address: 5DUnd4VPKWqEnbMEJ7CSnDUdikVkbfFZ6UqqJUAcgjf8g6ab
  restriction:
    remaining: 10000000000000 # leave this much in the sender, send the rest
- sender:
    alias: validator-003
    keystore:
      filePath: /home/fgimenez/workspace/w3f/validator-scripts/keystores/stash-3.json
      passwordPath: /home/fgimenez/Desktop/accountant/prodpass.txt
  receiver:
    alias: validator-rewards
    address: 5DUnd4VPKWqEnbMEJ7CSnDUdikVkbfFZ6UqqJUAcgjf8g6ab
  restriction:
    remaining: 10000000000000 # leave this much in the sender, send the rest
- sender:
    alias: validator-004
    keystore:
      filePath: /home/fgimenez/workspace/w3f/validator-scripts/keystores/stash-4.json
      passwordPath: /home/fgimenez/Desktop/accountant/prodpass.txt
  receiver:
    alias: validator-rewards
    address: 5DUnd4VPKWqEnbMEJ7CSnDUdikVkbfFZ6UqqJUAcgjf8g6ab
  restriction:
    remaining: 10000000000000 # leave this much in the sender, send the rest
- sender:
    alias: validator-005
    keystore:
      filePath: /home/fgimenez/workspace/w3f/validator-scripts/keystores/stash-5.json
      passwordPath: /home/fgimenez/Desktop/accountant/prodpass.txt
  receiver:
    alias: validator-rewards
    address: 5DUnd4VPKWqEnbMEJ7CSnDUdikVkbfFZ6UqqJUAcgjf8g6ab
  restriction:
    remaining: 10000000000000 # leave this much in the sender, send the rest
- sender:
    alias: validator-006
    keystore:
      filePath: /home/fgimenez/workspace/w3f/validator-scripts/keystores/stash-6.json
      passwordPath: /home/fgimenez/Desktop/accountant/prodpass.txt
  receiver:
    alias: validator-rewards
    address: 5DUnd4VPKWqEnbMEJ7CSnDUdikVkbfFZ6UqqJUAcgjf8g6ab
  restriction:
    remaining: 10000000000000 # leave this much in the sender, send the rest
- sender:
    alias: validator-007
    keystore:
      filePath: /home/fgimenez/workspace/w3f/validator-scripts/keystores/stash-7.json
      passwordPath: /home/fgimenez/Desktop/accountant/prodpass.txt
  receiver:
    alias: validator-rewards
    address: 5DUnd4VPKWqEnbMEJ7CSnDUdikVkbfFZ6UqqJUAcgjf8g6ab
  restriction:
    remaining: 10000000000000 # leave this much in the sender, send the rest
- sender:
    alias: validator-008
    keystore:
      filePath: /home/fgimenez/workspace/w3f/validator-scripts/keystores/stash-8.json
      passwordPath: /home/fgimenez/Desktop/accountant/prodpass.txt
  receiver:
    alias: validator-rewards
    address: 5DUnd4VPKWqEnbMEJ7CSnDUdikVkbfFZ6UqqJUAcgjf8g6ab
  restriction:
    remaining: 10000000000000 # leave this much in the sender, send the rest
- sender:
    alias: validator-009
    keystore:
      filePath: /home/fgimenez/workspace/w3f/validator-scripts/keystores/stash-9.json
      passwordPath: /home/fgimenez/Desktop/accountant/prodpass.txt
  receiver:
    alias: validator-rewards
    address: 5DUnd4VPKWqEnbMEJ7CSnDUdikVkbfFZ6UqqJUAcgjf8g6ab
  restriction:
    remaining: 10000000000000 # leave this much in the sender, send the rest
- sender:
    alias: validator-010
    keystore:
      filePath: /home/fgimenez/workspace/w3f/validator-scripts/keystores/stash-10.json
      passwordPath: /home/fgimenez/Desktop/accountant/prodpass.txt
  receiver:
    alias: validator-rewards
    address: 5DUnd4VPKWqEnbMEJ7CSnDUdikVkbfFZ6UqqJUAcgjf8g6ab
  restriction:
    remaining: 10000000000000 # leave this much in the sender, send the rest
- sender:
    alias: validator-011
    keystore:
      filePath: /home/fgimenez/workspace/w3f/validator-scripts/keystores/stash-11.json
      passwordPath: /home/fgimenez/Desktop/accountant/prodpass.txt
  receiver:
    alias: validator-rewards
    address: 5DUnd4VPKWqEnbMEJ7CSnDUdikVkbfFZ6UqqJUAcgjf8g6ab
  restriction:
    remaining: 10000000000000 # leave this much in the sender, send the rest
- sender:
    alias: validator-012
    keystore:
      filePath: /home/fgimenez/workspace/w3f/validator-scripts/keystores/stash-12.json
      passwordPath: /home/fgimenez/Desktop/accountant/prodpass.txt
  receiver:
    alias: validator-rewards
    address: 5DUnd4VPKWqEnbMEJ7CSnDUdikVkbfFZ6UqqJUAcgjf8g6ab
  restriction:
    remaining: 10000000000000 # leave this much in the sender, send the rest
- sender:
    alias: validator-013
    keystore:
      filePath: /home/fgimenez/workspace/w3f/validator-scripts/keystores/stash-13.json
      passwordPath: /home/fgimenez/Desktop/accountant/prodpass.txt
  receiver:
    alias: validator-rewards
    address: 5DUnd4VPKWqEnbMEJ7CSnDUdikVkbfFZ6UqqJUAcgjf8g6ab
  restriction:
    remaining: 10000000000000 # leave this much in the sender, send the rest
- sender:
    alias: validator-014
    keystore:
      filePath: /home/fgimenez/workspace/w3f/validator-scripts/keystores/stash-14.json
      passwordPath: /home/fgimenez/Desktop/accountant/prodpass.txt
  receiver:
    alias: validator-rewards
    address: 5DUnd4VPKWqEnbMEJ7CSnDUdikVkbfFZ6UqqJUAcgjf8g6ab
  restriction:
    remaining: 10000000000000 # leave this much in the sender, send the rest
- sender:
    alias: validator-015
    keystore:
      filePath: /home/fgimenez/workspace/w3f/validator-scripts/keystores/stash-15.json
      passwordPath: /home/fgimenez/Desktop/accountant/prodpass.txt
  receiver:
    alias: validator-rewards
    address: 5DUnd4VPKWqEnbMEJ7CSnDUdikVkbfFZ6UqqJUAcgjf8g6ab
  restriction:
    remaining: 10000000000000 # leave this much in the sender, send the rest
- sender:
    alias: validator-016
    keystore:
      filePath: /home/fgimenez/workspace/w3f/validator-scripts/keystores/stash-16.json
      passwordPath: /home/fgimenez/Desktop/accountant/prodpass.txt
  receiver:
    alias: validator-rewards
    address: 5DUnd4VPKWqEnbMEJ7CSnDUdikVkbfFZ6UqqJUAcgjf8g6ab
  restriction:
    remaining: 10000000000000 # leave this much in the sender, send the rest
- sender:
    alias: validator-017
    keystore:
      filePath: /home/fgimenez/workspace/w3f/validator-scripts/keystores/stash-17.json
      passwordPath: /home/fgimenez/Desktop/accountant/prodpass.txt
  receiver:
    alias: validator-rewards
    address: 5DUnd4VPKWqEnbMEJ7CSnDUdikVkbfFZ6UqqJUAcgjf8g6ab
  restriction:
    remaining: 10000000000000 # leave this much in the sender, send the rest
- sender:
    alias: validator-018
    keystore:
      filePath: /home/fgimenez/workspace/w3f/validator-scripts/keystores/stash-18.json
      passwordPath: /home/fgimenez/Desktop/accountant/prodpass.txt
  receiver:
    alias: validator-rewards
    address: 5DUnd4VPKWqEnbMEJ7CSnDUdikVkbfFZ6UqqJUAcgjf8g6ab
  restriction:
    remaining: 10000000000000 # leave this much in the sender, send the rest
- sender:
    alias: validator-019
    keystore:
      filePath: /home/fgimenez/workspace/w3f/validator-scripts/keystores/stash-19.json
      passwordPath: /home/fgimenez/Desktop/accountant/prodpass.txt
  receiver:
    alias: validator-rewards
    address: 5DUnd4VPKWqEnbMEJ7CSnDUdikVkbfFZ6UqqJUAcgjf8g6ab
  restriction:
    remaining: 10000000000000 # leave this much in the sender, send the rest
- sender:
    alias: validator-020
    keystore:
      filePath: /home/fgimenez/workspace/w3f/validator-scripts/keystores/stash-20.json
      passwordPath: /home/fgimenez/Desktop/accountant/prodpass.txt
  receiver:
    alias: validator-rewards
    address: 5DUnd4VPKWqEnbMEJ7CSnDUdikVkbfFZ6UqqJUAcgjf8g6ab
  restriction:
    remaining: 10000000000000 # leave this much in the sender, send the rest
- sender:
    alias: validator-021
    keystore:
      filePath: /home/fgimenez/workspace/w3f/validator-scripts/keystores/stash-21.json
      passwordPath: /home/fgimenez/Desktop/accountant/prodpass.txt
  receiver:
    alias: validator-rewards
    address: 5DUnd4VPKWqEnbMEJ7CSnDUdikVkbfFZ6UqqJUAcgjf8g6ab
  restriction:
    remaining: 10000000000000 # leave this much in the sender, send the rest
- sender:
    alias: validator-022
    keystore:
      filePath: /home/fgimenez/workspace/w3f/validator-scripts/keystores/stash-22.json
      passwordPath: /home/fgimenez/Desktop/accountant/prodpass.txt
  receiver:
    alias: validator-rewards
    address: 5DUnd4VPKWqEnbMEJ7CSnDUdikVkbfFZ6UqqJUAcgjf8g6ab
  restriction:
    remaining: 10000000000000 # leave this much in the sender, send the rest
- sender:
    alias: validator-023
    keystore:
      filePath: /home/fgimenez/workspace/w3f/validator-scripts/keystores/stash-23.json
      passwordPath: /home/fgimenez/Desktop/accountant/prodpass.txt
  receiver:
    alias: validator-rewards
    address: 5DUnd4VPKWqEnbMEJ7CSnDUdikVkbfFZ6UqqJUAcgjf8g6ab
  restriction:
    remaining: 10000000000000 # leave this much in the sender, send the rest
- sender:
    alias: validator-024
    keystore:
      filePath: /home/fgimenez/workspace/w3f/validator-scripts/keystores/stash-24.json
      passwordPath: /home/fgimenez/Desktop/accountant/prodpass.txt
  receiver:
    alias: validator-rewards
    address: 5DUnd4VPKWqEnbMEJ7CSnDUdikVkbfFZ6UqqJUAcgjf8g6ab
  restriction:
    remaining: 10000000000000 # leave this much in the sender, send the rest
- sender:
    alias: validator-025
    keystore:
      filePath: /home/fgimenez/workspace/w3f/validator-scripts/keystores/stash-25.json
      passwordPath: /home/fgimenez/Desktop/accountant/prodpass.txt
  receiver:
    alias: validator-rewards
    address: 5DUnd4VPKWqEnbMEJ7CSnDUdikVkbfFZ6UqqJUAcgjf8g6ab
  restriction:
    remaining: 10000000000000 # leave this much in the sender, send the rest
- sender:
    alias: validator-026
    keystore:
      filePath: /home/fgimenez/workspace/w3f/validator-scripts/keystores/stash-26.json
      passwordPath: /home/fgimenez/Desktop/accountant/prodpass.txt
  receiver:
    alias: validator-rewards
    address: 5DUnd4VPKWqEnbMEJ7CSnDUdikVkbfFZ6UqqJUAcgjf8g6ab
  restriction:
    remaining: 10000000000000 # leave this much in the sender, send the rest
- sender:
    alias: validator-027
    keystore:
      filePath: /home/fgimenez/workspace/w3f/validator-scripts/keystores/stash-27.json
      passwordPath: /home/fgimenez/Desktop/accountant/prodpass.txt
  receiver:
    alias: validator-rewards
    address: 5DUnd4VPKWqEnbMEJ7CSnDUdikVkbfFZ6UqqJUAcgjf8g6ab
  restriction:
    remaining: 10000000000000 # leave this much in the sender, send the rest
- sender:
    alias: validator-028
    keystore:
      filePath: /home/fgimenez/workspace/w3f/validator-scripts/keystores/stash-28.json
      passwordPath: /home/fgimenez/Desktop/accountant/prodpass.txt
  receiver:
    alias: validator-rewards
    address: 5DUnd4VPKWqEnbMEJ7CSnDUdikVkbfFZ6UqqJUAcgjf8g6ab
  restriction:
    remaining: 10000000000000 # leave this much in the sender, send the rest
- sender:
    alias: validator-029
    keystore:
      filePath: /home/fgimenez/workspace/w3f/validator-scripts/keystores/stash-29.json
      passwordPath: /home/fgimenez/Desktop/accountant/prodpass.txt
  receiver:
    alias: validator-rewards
    address: 5DUnd4VPKWqEnbMEJ7CSnDUdikVkbfFZ6UqqJUAcgjf8g6ab
  restriction:
    remaining: 10000000000000 # leave this much in the sender, send the rest
- sender:
    alias: validator-030
    keystore:
      filePath: /home/fgimenez/workspace/w3f/validator-scripts/keystores/stash-30.json
      passwordPath: /home/fgimenez/Desktop/accountant/prodpass.txt
  receiver:
    alias: validator-rewards
    address: 5DUnd4VPKWqEnbMEJ7CSnDUdikVkbfFZ6UqqJUAcgjf8g6ab
  restriction:
    remaining: 10000000000000 # leave this much in the sender, send the rest
- sender:
    alias: validator-031
    keystore:
      filePath: /home/fgimenez/workspace/w3f/validator-scripts/keystores/stash-31.json
      passwordPath: /home/fgimenez/Desktop/accountant/prodpass.txt
  receiver:
    alias: validator-rewards
    address: 5DUnd4VPKWqEnbMEJ7CSnDUdikVkbfFZ6UqqJUAcgjf8g6ab
  restriction:
    remaining: 10000000000000 # leave this much in the sender, send the rest
- sender:
    alias: validator-032
    keystore:
      filePath: /home/fgimenez/workspace/w3f/validator-scripts/keystores/stash-32.json
      passwordPath: /home/fgimenez/Desktop/accountant/prodpass.txt
  receiver:
    alias: validator-rewards
    address: 5DUnd4VPKWqEnbMEJ7CSnDUdikVkbfFZ6UqqJUAcgjf8g6ab
  restriction:
    remaining: 10000000000000 # leave this much in the sender, send the rest
- sender:
    alias: validator-033
    keystore:
      filePath: /home/fgimenez/workspace/w3f/validator-scripts/keystores/stash-33.json
      passwordPath: /home/fgimenez/Desktop/accountant/prodpass.txt
  receiver:
    alias: validator-rewards
    address: 5DUnd4VPKWqEnbMEJ7CSnDUdikVkbfFZ6UqqJUAcgjf8g6ab
  restriction:
    remaining: 10000000000000 # leave this much in the sender, send the rest
- sender:
    alias: validator-034
    keystore:
      filePath: /home/fgimenez/workspace/w3f/validator-scripts/keystores/stash-34.json
      passwordPath: /home/fgimenez/Desktop/accountant/prodpass.txt
  receiver:
    alias: validator-rewards
    address: 5DUnd4VPKWqEnbMEJ7CSnDUdikVkbfFZ6UqqJUAcgjf8g6ab
  restriction:
    remaining: 10000000000000 # leave this much in the sender, send the rest
- sender:
    alias: validator-035
    keystore:
      filePath: /home/fgimenez/workspace/w3f/validator-scripts/keystores/stash-35.json
      passwordPath: /home/fgimenez/Desktop/accountant/prodpass.txt
  receiver:
    alias: validator-rewards
    address: 5DUnd4VPKWqEnbMEJ7CSnDUdikVkbfFZ6UqqJUAcgjf8g6ab
  restriction:
    remaining: 10000000000000 # leave this much in the sender, send the rest

claims:
- alias: validator-000
  keystore:
    filePath: /home/fgimenez/workspace/w3f/validator-scripts/keystores/stash-0.json
    passwordPath: /home/fgimenez/Desktop/accountant/prodpass.txt
