logLevel: info
wsEndpoint: "ws://localhost:11000"
transactions:
- sender:
    alias: sender1
    address: 5CM4516HXdfAdWffkiDCBve7hukmNnP791cRf8kQNopeaWpX
    keystore:
      filePath: /home/fgimenez/Desktop/accountant/test.json
      passwordPath: /home/fgimenez/Desktop/accountant/password.txt
  receiver:
    alias: receiver1
    address: 5DwAurocRcvfdozAuyojRwYVy9k7h8yekrrBKaDdfEhN13sJ
  restriction:
    remaining: 950000000000000 # leave this much in the sender, send the rest
#- sender:
#    alias: sender1
#    address: 5CM4516HXdfAdWffkiDCBve7hukmNnP791cRf8kQNopeaWpX
#    keystore:
#      filePath: /home/fgimenez/Desktop/accountant/test.json
#      passwordPath: /home/fgimenez/Desktop/accountant/password.txt
#  receiver:
#    alias: receiver2
#    address: 5F7dw2gF9DfGoBVdaWfv8ZLTZHrj8wQ7JeSGsPFp7yNkuNdy
#  restriction:
#    desired: 10 # send desired - current_receiver_balance, if current_receiver_balance >= desired noop
