environments:
  production:
  ci:

repositories:
- name: w3f
  url: https://w3f.github.io/helm-charts/

releases:
- name: accountant
{{ if eq .Environment.Name "production" }}
  chart: w3f/accountant
{{ else }}
  chart: ../charts/accountant
{{ end }}
  values:
  - ./config/accountant.yaml.gotmpl
